SELECT INDIVIDUAL_ID
	,ROW_NUMBER() OVER(PARTITION BY INDIVIDUAL_ID ORDER BY is_primary desc ,XPTimeStamp DESC) AS ROW
	,EMAIL_ADDRESS
	,IS_PRIMARY
	,SEQ
	FROM dbo.EMAIL	E
	INNER JOIN ID.MonthEnd_DL_Load_Dates D ON D.dl_load_Date = E.DL_LOAD_DATE AND D.sequence = 1	
)

SELECT I.FIRST_NAME, I.LAST_NAME,I.INDIVIDUAL_ID as Primary_Individual_ID, MP.MEMBER_NBR,
-- primary address
A.Address1, A.Address2, A.city, A.[State], A.Zip_str, A.Zip4_str
--, Primary_Address = CONCAT_WS(', ', A.ADDRESS1, A.ADDRESS2, A.CITY, A.STATE, A.ZIP_STR)
,E.EMAIL_ADDRESS as Primary_Email
, Deceased = CASE WHEN Ex.DEATH_DATE IS NULL THEN NULL ELSE 'Y' END
, BANKRUPTCY = CASE WHEN Ex.W5 IS NULL THEN 0 ELSE 1 END
, Fiduciary = CASE WHEN Ex.Fiduciary = -1 THEN 'Y' ELSE NULL END
, Business = M.IsBusiness
, Written_Off_Loans = CASE WHEN L.WrittenOffCnt > 0 THEN 'Y' ELSE NULL END
, Charged_Off_Loans = CASE WHEN Account.ChargedOffCnt > 0 THEN 'Y' ELSE NULL END

FROM INDIVIDUALADDRESS IA
INNER JOIN ID.MonthEnd_DL_Load_Dates D ON IA.DL_LOAD_DATE = D.dl_load_Date AND D.sequence = 1
INNER JOIN Address A ON IA.ADDRESS_ID = A.ADDRESS_ID AND IA.DL_LOAD_DATE = A.DL_LOAD_DATE
INNER JOIN INDIVIDUAL I ON I.INDIVIDUAL_ID = IA.INDIVIDUAL_ID AND IA.DL_LOAD_DATE = I.DL_LOAD_DATE
INNER JOIN E ON I.INDIVIDUAL_ID = E.INDIVIDUAL_ID AND E.ROW = 1
INNER JOIN MEMBERSHIPPARTICIPANT MP ON MP.INDIVIDUAL_ID = I.INDIVIDUAL_ID AND MP.DL_LOAD_DATE = IA.DL_LOAD_DATE

CROSS APPLY
(
	SELECT IsBusiness = MAX(CASE WHEN M.Type = '10' THEN 'Y' ELSE NULL END)
	FROM  MEMBERSHIP M
	WHERE M.MEMBER_NBR = MP.MEMBER_NBR AND M.DL_LOAD_DATE = MP.DL_LOAD_DATE
) M
CROSS APPLY
(
	SELECT W5 = MAX(W5), DEATH_DATE = MAX(DEATH_DATE), Fiduciary = MAX(Fiduciary)
	FROM FCCU.Services_Exclusions Ex 
	WHERE Ex.MEMBER_NBR = MP.MEMBER_NBR
) Ex
CROSS APPLY
(
	SELECT WrittenOffCnt = SUM(CASE WHEN Loan_Type IN (98,206400,206403,206406,206409,206412) THEN 1 ELSE 0 END)
	, max(closed) as closed
	FROM LOAN
	WHERE MEMBER_NBR = MP.MEMBER_NBR AND DL_LOAD_DATE = IA.DL_LOAD_DATE
) L

CROSS APPLY
(
	select max(closed) as closed
	FROM SHARE
	WHERE MEMBER_NBR = MP.MEMBER_NBR AND DL_LOAD_DATE = IA.DL_LOAD_DATE
) S
CROSS APPLY
(
	SELECT ChargedOffCnt = COUNT(*)
	FROM SHAREPROPERTY
	WHERE DL_LOAD_DATE = IA.DL_LOAD_DATE AND VALUELIST_ITEM_DESCRIPTION LIKE '%negative%' AND MEMBER_NBR = mp.MEMBER_NBR AND SHARE_NBR IN (1,2,30,5,7,9)
) Account
-- only primary address
WHERE  IA.IS_PRIMARY = 1
-- *Remove closed accounts (no open deposit accounts or loans)
and l.closed != -1
and s.closed != -1;
